language: node_js
node_js:
  - "node"
addons:
  code_climate:
    repo_token: 1c6daf6072cc0641c0d8df48ba4dc7f1da4505f128d44e5dc99204b194d3e73f
script: npm run build:ci
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./reports/coverage/lcov.info
